### ISSUE TITLE
jEdit plugin setup throws error messages

### ISSUE THREAD

**Issue by Jazzpirate** [KWARC/MMT#52]
uninstalling:
deleting /home/raupi/.jedit/plugins/info.kwarc.mmt.jedit.MMTPlugin/startup.msl
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at info.kwarc.mmt.jeditsetup.Setup$.main(Setup.scala:95)
	at info.kwarc.mmt.jeditsetup.Setup.main(Setup.scala)

installing:
copying /home/raupi/lmh/MMT/deploy/jedit-plugin/plugin/plugins/info.kwarc.mmt.jedit.MMTPlugin/startup.msl to /home/raupi/.jedit/plugins/info.kwarc.mmt.jedit.MMTPlugin/startup.msl
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at info.kwarc.mmt.jeditsetup.Setup$.main(Setup.scala:95)
	at info.kwarc.mmt.jeditsetup.Setup.main(Setup.scala)

**Comment by Jazzpirate** [comment]
potentially related:
for some reason, SideKick doesn't parse some of the mmt documents. Klicking the "parse" button does nothing...?

**Comment by Jazzpirate** [comment]
the file does exist, so that's not it.
A "sbt deploy" in the src folder should package everything the right way as well, right?

**Comment by cmaeder** [comment]
`sbt install` directly copies the jars into (a jars subfolder of) the folder given in a file `jedit-settings-folder`

**Comment by Jazzpirate** [comment]
that's not the intended way for users though, is it? So, the error message above is still an issue?

**Comment by cmaeder** [comment]
I cannot reproduce the error message

**Comment by cmaeder** [comment]
the MMTPlugin.jar was not up-to-date
