### ISSUE TITLE
Weird stuff happening with MMT setup script under Windows

### ISSUE THREAD

**Issue by Jazzpirate** [KWARC/MMT#66]
Trying to setup that stuff on a students computer. First, the setup.bat yields the error stuff at the end. Afterwards, using the old setup routine for the jEdit plugin (and after verifying that all the jars are there), it says: 
"Java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "info.kwarc.mmt.jedit.MMTPlugin.log(Lscala/Function0;Lscala/Option;)V" the class loader (instance of org/gjt/sp/jedit/JARClassLoader) of the current class, info/kwarc/mmt/jedit/MMTPlugin, and the class loader (instance of org/gjt/sp/jedit/JARClassLoader) for interface info/kwarc/mmt/api/frontend/Logger have different Class objects for the type scala/Function0 used in the signature"

setup.bat yields:

using the following data
MMT system folder:     F:\qvod\MMT-gh-pages
MMT content folder:    F:\qvod\content
jEdit settings folder: C:\Users\Administrator\AppData\Roaming\jEdit

generating F:\qvod\MMT-gh-pages\deploy\main\startup.msl
done

cloning content repositories (by calling git)
user: log console finished
user: log+ oaf
user: log+ oaf finished
user: oaf root F:\qvod\content
user: oaf root F:\qvod\content  finished
user: file F:\qvod\MMT-gh-pages\deploy\main\startup.msl finished
user: oaf clone MMT/examples
oaf: sh --login -c "git clone http://gl.mathhub.info/MMT/examples.git MMT/ex
es" in F:\qvod\content
Exception in thread "main" java.io.IOException: Cannot run program "sh" (in
ctory "F:\qvod\content"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at info.kwarc.mmt.api.utils.ShellCommand$.runInOpt(ShellCommand.scal
)
        at info.kwarc.mmt.api.utils.ShellCommand$.runIn(ShellCommand.scala:4
        at info.kwarc.mmt.api.backend.OAF.info$kwarc$mmt$api$backend$OAF$$gi
F.scala:51)
        at info.kwarc.mmt.api.backend.OAF.clone(OAF.scala:84)
        at info.kwarc.mmt.api.frontend.Controller.info$kwarc$mmt$api$fronten
ntroller$$cloneRecursively(Controller.scala:538)
        at info.kwarc.mmt.api.frontend.Controller.handle(Controller.scala:61
        at info.kwarc.mmt.doc.Setup$.main(Setup.scala:46)
        at info.kwarc.mmt.doc.Setup.main(Setup.scala)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more

**Comment by cmaeder** [comment]
I think we agreed that windows is badly supported. At least "sh" and "git" must be installed.
Let's close this issue as long as it is not reproduced with a working "sh" and "git" installation.
