### ISSUE TITLE
Error on building .mmt files?

### ISSUE THREAD

**Issue by Jazzpirate** [KWARC/MMT#79]
calling 
        controller.handleLine("build PVS/Prelude mmt-omdoc")
...leads to the error below; my code is probably outdated - what should I call instead?

Terminal output:
archive: entering /home/raupi/lmh/MathHub/PVS/Prelude/src
archive: [source -> narration] /home/raupi/lmh/MathHub/PVS/Prelude/src/pvs.mmt -> /home/raupi/lmh/MathHub/PVS/Prelude/narration/pvs.omdoc
Exception in thread "main" java.lang.AbstractMethodError
	at info.kwarc.mmt.api.StructuralElement$class.$init$(OMDocElement.scala:30)
	at info.kwarc.mmt.api.documents.XRef.<init>(XRef.scala:14)
	at info.kwarc.mmt.api.documents.MRef.<init>(XRef.scala:33)
	at info.kwarc.mmt.api.documents.MRef$.apply(XRef.scala:38)
	at info.kwarc.mmt.api.parser.KeywordBasedParser.readTheory(StructureParser.scala:334)
	at info.kwarc.mmt.api.parser.KeywordBasedParser.info$kwarc$mmt$api$parser$KeywordBasedParser$$readInDocument(StructureParser.scala:677)
	at info.kwarc.mmt.api.parser.KeywordBasedParser$$anonfun$apply$1.apply$mcV$sp(StructureParser.scala:173)
	at info.kwarc.mmt.api.parser.KeywordBasedParser$$anonfun$apply$1.apply(StructureParser.scala:173)
	at info.kwarc.mmt.api.parser.KeywordBasedParser$$anonfun$apply$1.apply(StructureParser.scala:173)
	at info.kwarc.mmt.api.frontend.Logger$class.logGroup(Log.scala:21)
	at info.kwarc.mmt.api.parser.Parser.logGroup(Parser.scala:141)
	at info.kwarc.mmt.api.parser.KeywordBasedParser.apply(StructureParser.scala:172)
	at info.kwarc.mmt.api.parser.KeywordBasedParser.apply(StructureParser.scala:164)
	at info.kwarc.mmt.api.checking.TwoStepInterpreter.apply(Interpreter.scala:106)
	at info.kwarc.mmt.api.checking.Interpreter.importDocument(Interpreter.scala:29)
	at info.kwarc.mmt.api.archives.Importer.buildFile(Index.scala:40)
	at info.kwarc.mmt.api.archives.TraversingBuildTarget$$anonfun$info$kwarc$mmt$api$archives$TraversingBuildTarget$$buildAux$3.apply(BuildTarget.scala:213)
	at info.kwarc.mmt.api.archives.TraversingBuildTarget$$anonfun$info$kwarc$mmt$api$archives$TraversingBuildTarget$$buildAux$3.apply(BuildTarget.scala:198)
	at info.kwarc.mmt.api.archives.WritableArchive.traverse(Archive.scala:114)
	at info.kwarc.mmt.api.archives.WritableArchive.info$kwarc$mmt$api$archives$WritableArchive$$recurse$1(Archive.scala:100)
	at info.kwarc.mmt.api.archives.WritableArchive$$anonfun$4.apply(Archive.scala:107)
	at info.kwarc.mmt.api.archives.WritableArchive$$anonfun$4.apply(Archive.scala:107)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at info.kwarc.mmt.api.archives.WritableArchive.traverse(Archive.scala:107)
	at info.kwarc.mmt.api.archives.TraversingBuildTarget.info$kwarc$mmt$api$archives$TraversingBuildTarget$$buildAux(BuildTarget.scala:198)
	at info.kwarc.mmt.api.archives.TraversingBuildTarget.build(BuildTarget.scala:186)
	at info.kwarc.mmt.api.archives.TraversingBuildTarget.build(BuildTarget.scala:183)
	at info.kwarc.mmt.api.archives.BuildTarget.apply(BuildTarget.scala:73)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$archiveBuildAction$1$$anonfun$apply$18.apply(Controller.scala:528)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$archiveBuildAction$1$$anonfun$apply$18.apply(Controller.scala:528)
	at scala.Option.foreach(Option.scala:257)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$archiveBuildAction$1.apply(Controller.scala:528)
	at info.kwarc.mmt.api.frontend.Controller$$anonfun$archiveBuildAction$1.apply(Controller.scala:509)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at info.kwarc.mmt.api.frontend.Controller.archiveBuildAction(Controller.scala:509)
	at info.kwarc.mmt.api.frontend.Controller.handle(Controller.scala:593)
	at info.kwarc.mmt.api.frontend.Controller.handleLine(Controller.scala:465)
	at PVSTest$$anonfun$main$1.apply(PVSTest.scala:33)
	at PVSTest$$anonfun$main$1.apply(PVSTest.scala:33)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at PVSTest$.main(PVSTest.scala:33)
	at PVSTest.main(PVSTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by Jazzpirate** [comment]
solver by clean building MMT ^^
